version: "3.8"
services:
  rabbit:
    image: rabbitmq:3
    ports:
      - 127.0.0.1:5672:5672
  redis:
    image: redis:6
    ports:
      - 127.0.0.1:6379:6379
  postgres:
    image: postgres:11
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=fytdl
      - POSTGRES_USER=fytdl
      - POSTGRES_PASSWORD=fytdl
        #  fytdl-celery:
        #    depends_on:
        #      - rabbit
        #      - redis
        #      - postgres
        #    image: fytdl:local
        #    build:
        #      context: .
        #    command: ["celery"]
        #    volumes:
        #      - ./downloads:/var/run/fytdl/downloads
        #      - ./fytdl.cfg:/var/run/fytdl/fytdl.cfg:ro
        #    environment:
        #      - FYTDL_SETTINGS="/var/run/fytdl/fytdl.cfg"
        #      - FYTDL_REDIS_URL="redis://redis:6379"
        #      - FYTDL_CELERY_BROKER_URL="pyamqp://guest@rabbit"
        #      - FYTDL_CELERY_RESULTS_BACKEND="redis://redis:6379"
        #      - FYTDL_SQLALCHEMY_DATABASE_URI="postgresql://fytdl:fytdl@postgres:5432/fytdl"
